trigger:
  branches:
    include:
      - main

variables:
  - group: main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'

  - checkout: self

  - task: CopyFilesOverSSH@0
    inputs:
      sshEndpoint: 'myserviceconnection'
      sourceFolder: '$(System.DefaultWorkingDirectory)'
      contents: '**'
      targetFolder: $(APP_PATH)
      readyTimeout: '20000'
    displayName: 'Copy files to target server'
      
  - script: |
      mkdir -p ~/.ssh
      echo "$(SSH_PRIVATE_KEY)" | tr -d '\r' > ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa
      ssh-keyscan -H $(SSH_REMOTE_IP) >> ~/.ssh/known_hosts
    displayName: 'Setup SSH Key'

  - task: SSH@0
    inputs:
      sshEndpoint: 'myserviceconnection'
      runOptions: 'inline'
      inline: |
        rm -rf $(VENV_PATH)
        python3 -m venv $(VENV_PATH)        
      readyTimeout: '20000'
    displayName: 'Create virtual environment'

  - task: SSH@0
    inputs:
      sshEndpoint: 'myserviceconnection'
      runOptions: 'inline'
      inline: |
        # Find and kill the existing process on port 8061 without password prompt
        PID=$(lsof -t -i:8061)  
        if [ ! -z "$PID" ]; then
          echo "Stopping existing process on port 8061 (PID: $PID)"
          sudo /usr/bin/kill -9 $PID
        fi

        # Start a new Uvicorn process
        source $(VENV_PATH)/bin/activate
        pip install -r $(APP_PATH)/requirements.txt
        PYTHONPATH=$(APP_PATH) nohup uvicorn app:app --host 0.0.0.0 --port 8061 --reload > $(APP_PATH)/uvicorn.log 2>&1 &
        disown
      readyTimeout: '20000'
    displayName: 'Restart FastAPI App'
 