version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8062:8062"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
