# Use an official Python image
FROM python:3.9

# Set the working directory
WORKDIR /app

# Copy the application files
COPY app.py /app
COPY requirements.txt /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the application port
EXPOSE 8061

# Run the application
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8062"]
